### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by dessant** [kivy-garden/garden.roulettescroll#1]
Garden repositories must be released under the MIT license. Please tell us if you agree to release it with this license, or simply add the file, following this template: https://github.com/kivy-garden/kivy-garden.github.io/blob/master/LICENSE.

**Comment by eulerreich** [comment]
I agree

**Comment by dessant** [comment]
@eulerreich Thanks, i'll add the license file. Do you agree for the rest of your garden repos?

**Comment by eulerreich** [comment]
yes

**Comment by dessant** [comment]
Cool, thanks a lot.
